# Generated by Django 3.0.8 on 2020-10-26 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('block_no', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('block_name', models.CharField(blank=True, max_length=25, null=True)),
                ('no_of_floors', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'block',
            },
        ),
        migrations.CreateModel(
            name='Mess',
            fields=[
                ('mess_name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('person_in_charge', models.CharField(blank=True, max_length=32, null=True)),
                ('mess_contact', models.CharField(blank=True, max_length=10, null=True)),
                ('block_in', models.ForeignKey(blank=True, db_column='block_in', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tables.Block')),
            ],
            options={
                'db_table': 'mess',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('p_name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('p_contact', models.CharField(blank=True, max_length=10, null=True)),
                ('p_address', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'parent',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_no', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('room_type', models.CharField(blank=True, max_length=30, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('block_num', models.ForeignKey(blank=True, db_column='block_num', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tables.Block')),
            ],
            options={
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='Warden',
            fields=[
                ('emp_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('w_name', models.CharField(blank=True, max_length=32, null=True)),
                ('w_dob', models.DateField(blank=True, null=True)),
                ('w_address', models.CharField(blank=True, max_length=50, null=True)),
                ('w_contact', models.CharField(blank=True, max_length=10, null=True)),
                ('w_salary', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'warden',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('reg_no', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('s_name', models.CharField(blank=True, max_length=32, null=True)),
                ('s_address', models.CharField(blank=True, max_length=50, null=True)),
                ('s_contact', models.CharField(blank=True, max_length=10, null=True)),
                ('s_dob', models.DateField(blank=True, null=True)),
                ('s_school', models.CharField(blank=True, max_length=10, null=True)),
                ('s_program', models.CharField(blank=True, max_length=10, null=True)),
                ('parent_name', models.ForeignKey(blank=True, db_column='parent_name', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tables.Parent')),
                ('s_mess', models.ForeignKey(blank=True, db_column='s_mess', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tables.Mess')),
                ('s_room_no', models.ForeignKey(blank=True, db_column='s_room_no', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tables.Room')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('leave_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('leave_type', models.CharField(max_length=25)),
                ('reason', models.CharField(blank=True, max_length=25, null=True)),
                ('place_of_visit', models.CharField(blank=True, max_length=15, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, db_column='approved_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tables.Warden')),
                ('s_reg_no', models.ForeignKey(blank=True, db_column='s_reg_no', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tables.Student')),
            ],
            options={
                'db_table': 'leave_application',
            },
        ),
        migrations.AddField(
            model_name='block',
            name='warden_on_duty',
            field=models.ForeignKey(blank=True, db_column='warden_on_duty', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tables.Warden'),
        ),
    ]
